# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    #- develop    # disabling trigger for now; need to switch to schedule trigger
    - master
    #- releases/*
  paths:
    exclude:
    - deployment/*
    #- azure-pipelines.yml
    - README.md

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  imageName: 'dnsutil-curl'
  dockerRegistryServiceConnection: 'docker.io/ezlee'
  imageRepository: 'ezlee/$(imageName)' 
  containerRegistry: 'docker.io/ezlee'
  dockerfilePath: 'app/Dockerfile'
  tag: 'v0.$(Build.BuildId)'

  # Agent VM image name - Microsoft hosted agent
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build image
    pool:
      vmImage: $(vmImageName)
      workspace:
        clean: all
    steps:
    - task: Bash@3
      displayName: show workspace and other environment variables
      inputs:
        targetType: 'inline'
        script: 'env | sort'
#    - task: Bash@3
#      displayName: list files
#      inputs:
#        targetType: 'inline'
#        script: 'whoami; pwd ; ls -alh; which docker; docker version; cat $BUILD_SOURCESDIRECTORY/app/server.js'
#    - task: replacetokens@3
#      displayName: Add build number in server.js
#      inputs:
#        rootDirectory: $(Build.sourcesDirectory)/app
#        targetFiles: 'server.js'
#        keepToken: true
#        tokenPrefix: __
#        tokenSuffix: __
#    - task: Bash@3
#      displayName: show server.js file
#      inputs:
#        targetType: 'inline'
#        script: 'cat $BUILD_SOURCESDIRECTORY/app/server.js' 
#    - task: SonarCloudPrepare@1
#      displayName: Sonarcloud Prepare
#      inputs:
#        SonarCloud: 'SonarCloud'
#        organization: 'ezlee'
#        projectKey: 'ezlee_pipelines-javascript-docker'
#        projectName: 'pipeline-javascript-docker'
#        scannerMode: CLI
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: Bash@3
      displayName: Run Trivy Scan to scan docker images (2)
      inputs:
        targetType: 'inline'
        script: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy image --exit-code 0 --severity MEDIUM,HIGH --ignore-unfixed $(containerRegistry)/$(imageName):$(tag)
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy image --exit-code 1 --severity CRITICAL --ignore-unfixed $(containerRegistry)/$(imageName):$(tag)
#    - task: SonarCloudAnalyze@1
#      displayName: 'Run Code Analysis'
#    - task: SonarCloudPublish@1
#      displayName: 'Publish Quality Gate Result'
    - task: CmdLine@2
      displayName: tag the new build with latest tag
      inputs:
        script: 'docker tag $(imageRepository):$(tag) $(imageRepository):latest'
    - task: Docker@2
      displayName: push the latest tag
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
        tags: 'latest'
